### ISSUE TITLE
Add github-username to student results

### ISSUE THREAD

**Issue by racin** [autograde/quickfeed#334] opened 2020-09-23 15:25 UTC
I want to have a new column with the students username. The search should also filter results based on this new column.

The reasoning behind this is when a student send me a link to their github profile, I do not know their real name and thus cannot find them in autograder.

**Comment by meling** [comment] 2020-09-23 15:40
You can type the GitHub username in the search box and it will be found. Hence one solution that wouldn't take up more vertical space would be to just update the search box text from `Search for students` to `Search for student by name, student ID or GitHub username`, or something like that. Would that solve the problem?

**Comment by racin** [comment] 2020-09-23 15:52
Yes, I didn't know you could do that. Thanks!

Anyhow I see now that if I search for "gilje", the search will return 3 students, whilst only 1 student has this name. I suppose this is because there is a group with these 3 student inside.

**Comment by meling** [comment] 2020-09-23 17:15
Interesting, and yes that's possible. @0xf8f8ff is this something we should fix, or would it be too cumbersome? We could simply ignore the group name when searching for and listing students in the results view. Looks like [this code](https://github.com/autograde/quickfeed/blob/95cd0151e64f57461b24ddffb20535a69c062b4b/public/src/componentHelper.tsx#L153) is the cause. But I may be overlooking something here, such other uses of this function.

**Comment by 0xf8f8ff** [comment] 2020-09-23 17:18
The feature to look up students by the group name was requested last year by a teacher and added accordingly. It can be easily removed if it is no longer useful.

**Comment by meling** [comment] 2020-09-23 17:25
So it might make more sense if the group name is shown along side these students names, as proposed in #332.

**Comment by 0xf8f8ff** [comment] 2020-09-23 17:37
Right. Started working on #332.

**Comment by meling** [comment] 2020-10-31 11:41
Closing this as it was solved via #332

**Closed by meling** 2020-10-31 11:41 UTC
